### ISSUE TITLE
Tales of Bersia Cheat are not working for Artemis 

### ISSUE THREAD

**Issue by pftmclub** [bucanero/ArtemisPS3#11]
Hello, i tried to turn on "Max Money on Change" , "Max Item on Change" to "constant" or "once".
Whenever i tried to attach the cheat on my tales of bersia , the money and item doesn't change anything after i buy or sell an item to change the money.

I tried it on version 1.00 or 1.02 and none of them working. Is there anyway to find an value that working just like VitaCheat or CheatEngine ?

**Comment by bucanero** [comment]
I didn't create those cheats so I can't help with that

if you want to create/find codes and cheats for Artemis, the only tool I know is using [NetCheat](https://github.com/Dnawrkshp/NetCheatPS3)

Here's a tutorial for NetCheat made by @Dnawrkshp himself
https://www.youtube.com/watch?v=2dxuoLTA_Lk

**Comment by bucanero** [comment]
btw, there are some hacked PS3 save-games for Tales of Berseria around the web, but in that case you'd have to use Apollo to resign them

also, you'd loose your own progress, as those files might be at the start/middle/end of the game.

**Comment by bucanero** [comment]
oh well I was digging thru the .ncl files and it seems that were more codes for Tales of Berseria hidden 😄 

I've just uploaded a new file for the v1.02 version of the game in 14df8ad137193ff408bd5d1991630919427e8ee0

if you want to try, use the `Online database` option in Artemis and check the "tales of berseria v1.02" cheats. I've tested the `Max money on change` and it worked fine. (you can also transfer the .ncl file manually)
