### ISSUE TITLE
ps3 serius sam 3 netcheat 

### ISSUE THREAD

**Issue by rambooo9000** [bucanero/ArtemisPS3#18]
Serious Sam 3: BFE HELLO BUCANERO :))))
NPUB31165 V1.00
ölümsüz
0
B 00010000 04000000
B 4BBA396D6000000080630000 4BBA396D6000000060000000
#
sınırsız mermi
0
B 00010000 04000000
B 4B9EE4E16000000080630000 4B9EE4E16000000090630000
#

**Comment by bucanero** [comment]
Thanks! the codes have been added in e8fdffb823d96871cff878aafa4307f362876b45
