### ISSUE TITLE
minecraft v1.04 codes

### ISSUE THREAD

**Issue by rambooo9000** [bucanero/ArtemisPS3#25]
Unlimited Health
0
0 004480FC 60000000
0 0047F03C 60000000
0 00447D6C 60000000
#
Unlimited resources
0
0 003FCFBC 60000000
#
Infinite food
0
0 003D4004 60000000
0 003D3E4C 60000000
#
Infınite arrows
0
0 003E8648 60000000
#
minecraft v1.04

**Comment by bucanero** [comment]
These codes are already available:
https://github.com/bucanero/ArtemisPS3/blob/master/docs/codes/Minecraft%20NPUB31419%2001.04.ncl
