### ISSUE TITLE
Can't inject cheats

### ISSUE THREAD

**Issue by Rage4Dayz96** [bucanero/ArtemisPS3#37]
I can't inject cheats when playing a game, the "Start To Attach" doesn't show up, also when I'm in
Artemis and use "Start Game" my PS3 beeps two times and not one.

**Comment by bucanero** [comment]
the beeps mean that the plugin couldn't be loaded, so without Artemis plugin cheats won't work. There's an issue with your ps3 setup. To load the cheat plugin, Artemis needs PS3MAPI working

you can also load the plugin manually on boot: edit the `boot_plugins.txt` file and add the plugin path
`/dev_hdd0/game/ART.../USRDIR/artemis_ps3.sprx`

**Comment by Rage4Dayz96** [comment]
> the beeps mean that the plugin couldn't be loaded, so without Artemis plugin cheats won't work. There's an issue with your ps3 setup. To load the cheat plugin, Artemis needs PS3MAPI working
> 
> you can also load the plugin manually on boot: edit the `boot_plugins.txt` file and add the plugin path `/dev_hdd0/game/ART.../USRDIR/artemis_ps3.sprx`

Sorry for the super late reply, I've tried to do what you said but still not working.

**Comment by Rage4Dayz96** [comment]
> the beeps mean that the plugin couldn't be loaded, so without Artemis plugin cheats won't work. There's an issue with your ps3 setup. To load the cheat plugin, Artemis needs PS3MAPI working
> 
> you can also load the plugin manually on boot: edit the `boot_plugins.txt` file and add the plugin path `/dev_hdd0/game/ART.../USRDIR/artemis_ps3.sprx`

All good now, got it working.
