### ISSUE TITLE
How to solve it?!

### ISSUE THREAD

**Issue by azmeer830216** [bucanero/ArtemisPS3#43]
Hello..
Newbie here....

"You should hear a single beep (if you hear three MAMBA failed to install)"

- I heared it 3 beep and cheat didnt work
- How to solve it??
- Is there anything that i have to install on my ps3??
- Running rebug 4.++ (Sorry forgot about it)
- I try using Artemis r5 right now and its working just fine.

Please tell me how to solve it....till i hear a single beep when i launch the artemis for the the game...

Thanks in advanced!

**Comment by Rage4Dayz96** [comment]
I had the same issue, COBRA was disabled for some reason and I enable it again and now it works so check your settings and make sure nothing is turned off 

bucanero said this in my post 
the beeps mean that the plugin couldn't be loaded, so without Artemis plugin cheats won't work. There's an issue with your ps3 setup. To load the cheat plugin, Artemis needs PS3MAPI working

you can also load the plugin manually on boot: edit the boot_plugins.txt file and add the plugin path
/dev_hdd0/game/ART.../USRDIR/artemis_ps3.sprx
