### ISSUE TITLE
Artemis Hard Crashes PS3

### ISSUE THREAD

**Issue by Rage4Dayz96** [bucanero/ArtemisPS3#54]
I'm not sure if you can help me with this but my PS3 hard crashes when trying to use any cheats for the God of War Collection (BCE500791) 

Is there any way to fix it or are the cheats bad?
Thank You

**Comment by bucanero** [comment]
you could try the different plugins versions, but if the cheats still crash the PS3 then it's probably a bad code (either for a different version or patch) so you'll need new codes or a different version of the game.

**Comment by Rage4Dayz96** [comment]
> you could try the different plugin versions, but if the cheats still crash the PS3 then it's probably a bad code (either for a different version or patch) so you'll need new codes or a different version of the game.
> 

Hello, sorry for the late reply. I tried using different plugins but my PS3 still hard crashes, I also tried a different game version and it still crashes the PS3.

**Comment by bucanero** [comment]
Then the cheat codes are bad, you'll need new working codes. I can't help with that, but you could ask on forums if someone can create new codes.

**Comment by Rage4Dayz96** [comment]
> Then the cheat codes are bad, you'll need new working codes. I can't help with that, but you could ask on forums if someone can create new codes. 

What forums are you talking about, on here or somewhere else? Thank you
