### ISSUE TITLE
Constant write not working?

### ISSUE THREAD

**Issue by Cri4Key** [bucanero/ArtemisPS3#63]
I am trying to make my own cheats for the game PlayStation All-Stars Battle Royale.
What I am trying to do is apply a cheat to force load a scrapped arena that is still in the game. To do that, I need to change the values in a certain address that works as it follows: when an arena/level is selected in the game a value for the selected level is written, and after it's read to locate the right file to load, then the level starts loading.

For the cheat to work properly I need to prevent the game from writing on the address when a level is selected. In Artemis I highlight the cheat, toggle it on, and choose constant mode to achieve this, but the cheat just won't work. The cheat itself is correct, as using it on NetCheat on my PC it works properly by enabling constant write there.

Inspecting the memory I can see that when I attach Artemis the values change properly, but the moment I choose the level to run the game overwrites the values with its own. So the cheat is working, but not in constant write mode. Why is that? I am on 4.84 Rebug DEX, using latest Artemis r6.3, and plugin mode Artemis r5 (tho I tried all the different available ones with no success). Only other plugins loaded along Artemis are webman MOD and PSNPatch.

**Comment by bucanero** [comment]
Constant write doesn't work on the `r5 plugin`. AFAIK the only plugin that supports constant write properly is the `mod/haxxen` one. If you tried and didn't work, then the only thing left to try would be the new webman MOD that supports artemis cheat codes.
Then you don't need to use any artemis plugins and just use the embedded code on webman Mod. Keep in mind I have no idea if wMM supports constant write or not.

**Comment by Cri4Key** [comment]
Mmh nevermind, I tried again and seems that mod/haxxen works properly. Maybe I overlooked it during the times I tried to get it working and also while trying to get the cheat right. Or maybe I tried it and was supposed to reboot after changing? In any case, good to know that the defaulr r5 plugin doesn't support constant write, I didn't see it written anywhere. Thank you for answering 😄
