### ISSUE TITLE
Artemis does not install cheats when launched for first time

### ISSUE THREAD

**Issue by Letsplay1108** [bucanero/ArtemisPS3#66]
Should I just drag my own ncl files?

**Comment by bucanero** [comment]
you're not providing any details, installed version, firmware, etc++

assuming you installed 6.3, do you have a file `/USRDIR/CACHE/cheatdb.zip` on the Artemis HDD folder ?
also, if you open the "Options" menu, there's an option to "Update Local Cheats". If the ps3 has internet access, it should download and update the local database.

**Comment by Letsplay1108** [comment]
Oh im sorry, im on the latest version, hfw 4.89, I tried updating local cheats but didn't know where to find the cheatdb.zip

**Comment by bucanero** [comment]
"Update Local Cheats" connects to internet and downloads the cheat pack directly. Did you try 'online db' ? you can get the latest codes there.

or do it manually, https://github.com/bucanero/ArtemisPS3/blob/master/docs/cheatdb.zip
