### ISSUE TITLE
Possibility to add ps1 codebreaker codes to aretemis for ps1 classics

### ISSUE THREAD

**Issue by Codythedragonrude** [bucanero/ArtemisPS3#74]
This would make it easier as the current webman mod method of using web browser to disc swap does not work the codes don't stay in memory after codebreaker boots the ps1 game

Is it possible to do this
Or
Do ps1 classics load in a way that makes aretemis code injection impossible?

**Comment by stinger101mg** [comment]
dude you have to not close out of the game when you swap the discs, load up
code breaker, choose codes desired, get to the 'swap to game disc'
notification, then use the webman page to swap to desired disc, it will
error the first time, click it again and it will load your game, then in
the codebreaker emulation click x to load game disc. it will work if you
follow these steps directly and not close out of code breaker all together
then load up another game, if you do so the codes will not stay in memory
and you will load up your game without the desired codes

**Comment by stinger101mg** [comment]
it also goes without saying you cannot do the swap on the console in game,
you must have your ps3 hooked up to wifi and load the webman webpage via a
device connected to the same wifi, use that device to swap the disc then on
the console click x to load the game disc
