### ISSUE TITLE
Start to attach is not working [CEX 4.90]

### ISSUE THREAD

**Issue by voicenoise** [bucanero/ArtemisPS3#80]
Hello Everyone

i have a problem on my slim with cfw 4.90

When I select a cheat code and press start game, then start the game the following message popup appears "start to attach" 
But i can't activated it with the start button.

I have tried all versions from r5 to 6.3 and it definitely does not work and in options at plugin versions like webMAN MOD, Artemis r5, Artemis r6, mod/Haxxen, Joker Select.

It seems that artemis does not recognize the start button. 
Exept unique Joker Select. there the Start Button is working, but the codes is not working in this mode.
Does anyone have the same problem and possibly a solution?

System: PS3 Slim webMAN 1.47.45 MOD 4.90 CEX Cobra 8.4 (NTFS) [Rebug-PS3MAPI]

**Comment by goldug** [comment]
Try pressing the home (playstation logo) button first, that works for me.

**Comment by voicenoise** [comment]
I tried all the buttons, but I didn't expect to use home and then start.
It's a bit awkward but it works.
I hope that this will be fixed in the next version.
Thanks for your help

**Comment by goldug** [comment]
> I tried all the buttons, but I didn't expect to use home and then start. It's a bit awkward but it works. I hope that this will be fixed in the next version. Thanks for your help

Yeah, it's always been like that for me, never bothered to make a bug report. I can understand why it is like this, if you don't want to attach for some reason and you need to pause the game for instance.
If anything, it should be added to the manual.
